### ISSUE TITLE
Write to USB device?

### ISSUE THREAD

**Issue by metanav** [KurtE/GIGA_USBHostMBed5_devices#10]
Does this library support sending bytes to a connected USB device? Any minimal example?

**Comment by KurtE** [comment]
Again, I should note, that this library is so far mostly an experiment to see if a few of us can get some basic devices to work properly on top of the Arduino_USBHostMbed5 library, that is used on the Arduino GIGA and I believe Portenta H7 (maybe others as well).

I was curious if I could get some simple things like keyboards and Mice to work and not use the other library that was setup on the GIGA for that.  Some of this requires my own fork/branch of the main Arduino library, I am currently waiting on seeing if another github user has some success fixing some other issues as well.

>Does this library support sending bytes to a connected USB device? Any minimal example?

Probably, but probably depends on exactly you are asking about:  For example if a device you are connecting is some form of Serial communications like device (CDC ACM, FTDI, PL2303...), then there is a class in there that appears to work.  Example sketch is included that sends and receives stuff from it to the Host your Arduino board is connected to.

I am still having some issues with some other devices like keyboards, when I try to send them control messages, like to update their LEDs.

Sorry not sure if I answered your question or not.

**Comment by metanav** [comment]
Thank you for your reply. I am using the example USBHostSerialToSerial. It recognizes the device which is a RPLidar A1 connected via a USB-to-Serial adapter. I can use this directly on my Mac USB and it works but when I use it on Giga R1 USB A and send the bytes 0xA5 0x50 that should return some info from the device but it does not print anything. How can I debug whether the bytes are being sent correctly?

```
Starting USB host Serial device test...
VID: 10C4, PID: EA60 Silex CP210X

.connect hser_device_found

CP210x 0x41, 0, 1

USB host Serial device(10c4:ea60) connected trying begin

Baud: 115200

USBHostSerialDevice::begin - buffered writes

CP210x 0x41, 0, 1

*** Serial does not support availableForWrite ***
```

**Comment by metanav** [comment]
After setting DTR to false, the Giga is able to send and receive bytes. Thanks!
